django_/aw_kedro/urls.py
from django.urls import path
from . import views

app_name = "aw_kedro"
urlpatterns = [
    path("ali/", views.ali, name="ali"),
    path("", views.base, name="base"),
    path("register/", views.register, name="register"),
    path("awk/", views.tf_sentiment, name="tf_test"),
]

django_/dj_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("", include("aw_kedro.urls"),name='home'),
    path('polls/', include('polls.urls')),
    path("admin/", admin.site.urls),
]

django_/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),]

# urlpatterns = [
#     path("", views.IndexView.as_view(), name="index"),
#     path("<int:pk>/", views.DetailView.as_view(), name="detail"),
#     path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
#     path("<int:question_id>/vote/", views.vote, name="vote"),
# ]

django_/aw_kedro/models.py
from django.db import models

class Submit(models.Model):
    text = models.CharField(max_length=200)
    rating = models.FloatField()
    time = models.DateTimeField("date published")
    def __str__(self):
        return self.text

django_/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

django_/aw_kedro/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Submit

import tensorflow as tf
import numpy as np
import pandas as pd
import joblib
import pickle


from mtranslate import translate




# submit_list = Submit.objects.filter()

def tf_sentiment(request):
    try:
        post_string = request.POST["input_text_name"]
        emotion_rating = 123
        submit = Submit(text = post_string,rating = emotion_rating,time=timezone.now())
        submit.save()
        submit_list = Submit.objects.all()
        submit_list = reversed(submit_list)
        context = {"emotion_rating": emotion_rating,"input_text":post_string,"submit_list":submit_list}
    except:
        submit_list = Submit.objects.all()
        submit_list.delete()
        emotion_rating = ''
        context = {"emotion_rating": '',"editable_text":'',"submit_list":submit_list}
    return render(request, "ali.html", context)

def ali(request):
    context = {}
    return render(request, "ali.html",context)

def base(request):
    context = {}
    return render(request, "base.html",context)

def register(request):
    context = {}
    return render(request, "register.html",context)

django_/polls/views.py
from django.http import Http404,HttpResponse, HttpResponseRedirect
from django.shortcuts import render,HttpResponse,get_object_or_404
from django.template import loader
from django.urls import reverse
from django.db.models import F
from django.views import generic

from polls.models import Choice, Question

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     template = loader.get_template("polls/index.html")
#     context = {
#         "latest_question_list": latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

django_/aw_kedro/templates/about.html
{% extends "ali.html" %}

{% block title %}关于我们 - 红领巾{% endblock %}

{% block content %}
<h1>关于我们</h1>
<p>我们是党的接班人</p>
{% endblock %}

django_/aw_kedro/templates/ali.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>注册页面</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="logo">主页名称</div>
        <nav>
            <a href="">首页</a>
            <a href="#">产品</a>
            <a href="#">文档</a>
            <a href="#">关于</a>
            <a href="#">登陆</a>
        </nav>
    </header>

    <main>
        <h1>注册</h1>
        <form method="post">
            {% csrf_token %}
            <label for="username">用户名:</label>
            <input type="text" id="username" name="username" required><br>
            <label for="email">电子邮件:</label>
            <input type="email" id="email" name="email" required><br>
            <label for="password">密码:</label>
            <input type="password" id="password" name="password" required><br>
            <button type="submit">注册</button>
        </form>
    </main>

    <footer>
        <p>页脚内容</p>
    </footer>
</body>
</html>

django_/aw_kedro/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>主页</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="logo">主页名称</div>
        <nav>
            <a href="#">首页</a>
            <a href="#">产品</a>
            <a href="#">文档</a>
            <a href="#">关于</a>
            <a href="{% url 'aw_kedro:register' %}">注册</a>
            <a href="#">登陆</a>
        </nav>
    </header>

    <main>
        <h1>欢迎来到主页</h1>
        <p>这里是正文内容。</p>
    </main>

    <footer>
        <p>页脚内容</p>
    </footer>
</body>
</html>

django_/aw_kedro/templates/home.html
<!DOCTYPE html>
{% extends 'ali.html' %}

<html>

<div id="container" style="width:auto">

<div id="header" style="background-color:#FFA500;">
<h1 style="margin-bottom:0;">主要的网页标题</h1></div>

<div id="menu" style="background-color:#FFD700;height: 500px;;width:100px;float:left;">
<b>caigang</b><br>
asdf</div>


</div>
 
</html>

django_/aw_kedro/templates/index.html
<style>
    .container {
        display: flex;
    }

    .form-container {
        flex: 1;
        margin-right: 20px;
    }

    .list-container {
        flex: 1;
        overflow-y: scroll;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        max-height: 650; /* 设置最大高度，超过则显示滚动条 */
    }

    form {
        max-width: 800px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
    }

    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
    }

    textarea {
        display: block;
        width: 100%;
        height: 200px;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: none;
        font-size: 16px;
        font-family: Arial, sans-serif;
    }

    listtextarea {
        display: block;
        width: 98%;
        height: auto;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: none;
        font-size: 16px;
        font-family: Arial, sans-serif;
    }

    input[type="text"] {
        display: block;
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        box-sizing: border-box;
    }

    input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #3e8e41;
    }

    .list-item {
        margin-bottom: 10px;
    }
    
</style>

<div class="container">
    <div class="form-container">
        <form action="{% url 'aw_kedro:tf_test' %}" method="POST">
            {% csrf_token %}
            <label for="input_text_id">请输入测试文本:</label>
            <textarea id="input_text_id" name="input_text_name">{{ input_text }}</textarea>

            <label for="emotion_rating_id">情绪分数:(范围:0-1,低分代表消极,高分代表积极)</label>
            <input type="text" id="emotion_rating_id" name="emotion_rating_name" value="{{ emotion_rating }}" readonly />

            <input type="submit" value="提交" />
        </form>
    </div>
    <div class="list-container">
        <h3>历史记录:</h3>
        <div class="list-item">
            {% for submit in submit_list %}
            <listtextarea>{{ submit.text }}</listtextarea>
            <p>&nbsp;&nbsp;情绪分数:{{ submit.rating }}&nbsp;&nbsp;&nbsp;&nbsp; 时间:{{submit.time}}</p>
            {% endfor %}
        </div>
    </div>
</div>

django_/aw_kedro/templates/login.html
{% extends "ali.html" %}

{% block title %}关于我们 - 红领巾{% endblock %}

{% block content %}
<body>
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
    <div class="login-container">
        <h1>登录</h1>
        <form action="#" method="POST">
            <input type="text" name="username" placeholder="用户名" required><br>
            <input type="password" name="password" placeholder="密码" required><br>
            <button type="submit">登录</button>
        </form>
        <div class="links">
            <a href="signUp">注册</a>
        </div>
    </div>
</body>
{% endblock %}

django_/aw_kedro/templates/mode_test.html
<style>
    .container {
        display: flex;
    }

    .form-container {
        flex: 1;
        margin-right: 20px;
    }

    .list-container {
        flex: 1;
        overflow-y: scroll;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        max-height: 650; /* 设置最大高度，超过则显示滚动条 */
    }

    form {
        max-width: 800px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
    }

    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
    }

    textarea {
        display: block;
        width: 100%;
        height: 200px;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: none;
        font-size: 16px;
        font-family: Arial, sans-serif;
    }

    listtextarea {
        display: block;
        width: 98%;
        height: auto;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: none;
        font-size: 16px;
        font-family: Arial, sans-serif;
    }

    input[type="text"] {
        display: block;
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
        font-family: Arial, sans-serif;
        box-sizing: border-box;
    }

    input[type="submit"] {
        background-color: #4CAF50;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #3e8e41;
    }

    .list-item {
        margin-bottom: 10px;
    }
    
</style>

<div class="container">
    <div class="form-container">
        <form action="{% url 'aw_kedro:st_test' %}" method="POST">
            {% csrf_token %}
            <label for="input_text_id">请输入测试文本:</label>
            <textarea id="input_text_id" name="input_text_name">{{ input_text }}</textarea>

            <label for="emotion_rating_id">情绪分数:(范围:0-1,低分代表消极,高分代表积极)</label>
            <input type="text" id="emotion_rating_id" name="emotion_rating_name" value="{{ emotion_rating }}" readonly />

            <input type="submit" value="提交" />
        </form>
    </div>
    <div class="list-container">
        <h3>历史记录:</h3>
        <div class="list-item">
            {% for submit in submit_list %}
            <listtextarea>{{ submit.text }}</listtextarea>
            <p>&nbsp;&nbsp;情绪分数:{{ submit.rating }}&nbsp;&nbsp;&nbsp;&nbsp; 时间:{{submit.time}}</p>
            {% endfor %}
        </div>
    </div>
</div>

django_/aw_kedro/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>注册页面</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <div class="logo">主页名称</div>
        <nav>
            <a href="{% url 'aw_kedro:base' %}">首页</a>
            <a href="#">产品</a>
            <a href="#">文档</a>
            <a href="#">关于</a>
            <a href="#">登陆</a>
        </nav>
    </header>

    <main>
        <h1>注册</h1>
        <form method="post">
            {% csrf_token %}
            <label for="username">用户名:</label>
            <input type="text" id="username" name="username" required><br>
            <label for="email">电子邮件:</label>
            <input type="email" id="email" name="email" required><br>
            <label for="password">密码:</label>
            <input type="password" id="password" name="password" required><br>
            <button type="submit">注册</button>
        </form>
    </main>

    <footer>
        <p>页脚内容</p>
    </footer>
</body>
</html>

django_/aw_kedro/templates/sign_up.html
{% extends "base.html" %}

{% block title %}关于我们 - 红领巾{% endblock %}

{% block content %}
<title>sb</title> 
</head>
<body>
    <h2>表单</h2>

    <form action="/" method="post">
        <!-- 文本输入框 -->
        <label for="name">用户名:</label>
        <input type="text" id="name" name="name" required>
        <br>

        <!-- 密码输入框 -->
        <label for="password">密码:</label>
        <input type="password" id="password" name="password" required="True">
        <br>

        <!-- 单选按钮 -->
        <label>性别:</label>
        <input type="radio" id="male" name="gender" value="male" checked>
        <label for="male">男</label>
        <input type="radio" id="female" name="gender" value="female">
        <label for="female">女</label>
        <br>

        <label for="name">邮箱:</label>
        <input type="text" id="name" name="name" required>
        <br>

        <label for="country">国家:</label>
        <select id="country" name="country">
            <option value="cn">CN</option>
            <option value="usa">USA</option>
            <option value="uk">UK</option>
        </select><br>

        <label for="country">安全问题:</label>
        <select id="country" name="country">
            <option value="cn">我出生的城市</option>
            <option value="usa">我最爱的宠物的名字</option>
            <option value="uk">我的小学校名</option>
        </select><br>

        <label for="name">安全问题答案:</label>
        <input type="text" id="name" name="name" required>
        <br>

        <input type="checkbox" id="subscribe" name="subscribe" checked>
        <label for="subscribe">订阅推送信息</label>
        <br>
        
        <input type="submit" value="提交">
    </form>

</body>
{% endblock %}

django_/aw_kedro/templates/user.html
{% extends "ali.html" %}

{% block title %}关于我们 - 红领巾{% endblock %}

{% block content %}
<title>sb</title> 
</head>
<body>
    <h2>表单</h2>
    <form action="/" method="post">
        <label for="name">用户名:</label><br>
        <label for="password">密码:</label>

        <br>
        <label>性别:</label><br>
        <label for="country">国家:</label><br>
        <input type="submit" value="注销"><br>
    </form>

</body>
{% endblock %}

django_/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

django_/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django_/polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>